from enum import StrEnum


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    RETRY_WAIT = "RETRY_WAIT"
    DEAD = "DEAD"
    CANCELLED = "CANCELLED"


class JobType(StrEnum):
    CLASSIFY_ASSET = "CLASSIFY_ASSET"
    CLASSIFY_ASSET_FROM_OM = "CLASSIFY_ASSET_FROM_OM"
    AGENT_CLASSIFY = "AGENT_CLASSIFY"
    CREATE_OM_SUGGESTIONS = "CREATE_OM_SUGGESTIONS"
    APPLY_CONFIRMED_TAGS = "APPLY_CONFIRMED_TAGS"

    SYNC_RANGER_POLICIES = "SYNC_RANGER_POLICIES"
    SYNC_RANGER_TAGS = "SYNC_RANGER_TAGS"

    # Kept temporarily so already-queued pre-v0.6 jobs remain claimable.
    RECONCILE_RANGER = "RECONCILE_RANGER"

    DISCOVER_UNCLASSIFIED_ASSETS = "DISCOVER_UNCLASSIFIED_ASSETS"


class ClassificationSource(StrEnum):
    DETERMINISTIC = "DETERMINISTIC"
    AGENT = "AGENT"


class ClassificationAction(StrEnum):
    NONE = "NONE"
    OPENMETADATA_SUGGESTION = "OPENMETADATA_SUGGESTION"
    AUTO_APPLY = "AUTO_APPLY"
    AGENT_FALLBACK = "AGENT_FALLBACK"


class ReconciliationAction(StrEnum):
    DRY_RUN = "DRY_RUN"
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    NO_CHANGE = "NO_CHANGE"
    DRIFT_REPAIR = "DRIFT_REPAIR"
    DISABLE = "DISABLE"
    DELETE = "DELETE"
    FAILED = "FAILED"
