"""initial governance schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-07-29
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_key', sa.String(length=255), nullable=False),
    sa.Column('verification_group_id', sa.String(length=64), nullable=False),
    sa.Column('identity', sa.String(length=255), nullable=False),
    sa.Column('expected_allowed', sa.Boolean(), nullable=False),
    sa.Column('observed_allowed', sa.Boolean(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('query_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('error_class', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_verifications_policy_key'), 'access_verifications', ['policy_key'], unique=False)
    op.create_index(op.f('ix_access_verifications_verification_group_id'), 'access_verifications', ['verification_group_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=255), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_object', 'audit_events', ['object_type', 'object_id', 'created_at'], unique=False)
    op.create_table('governance_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=128), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_governance_jobs_idempotency')
    )
    op.create_index('ix_governance_jobs_claim', 'governance_jobs', ['status', 'available_at', 'priority', 'created_at'], unique=False)
    op.create_table('governance_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('proposer_id', sa.String(length=255), nullable=False),
    sa.Column('proposer_name', sa.String(length=255), nullable=False),
    sa.Column('reviewer_id', sa.String(length=255), nullable=True),
    sa.Column('reviewer_name', sa.String(length=255), nullable=True),
    sa.Column('target_entity_type', sa.String(length=64), nullable=False),
    sa.Column('target_fqn', sa.String(length=1024), nullable=False),
    sa.Column('field_path', sa.String(length=1024), nullable=True),
    sa.Column('requested_change', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_version', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_governance_proposals_status_created', 'governance_proposals', ['status', 'created_at'], unique=False)
    op.create_table('policy_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active_version', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_key')
    )
    op.create_table('policy_reconciliations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_key', sa.String(length=255), nullable=False),
    sa.Column('source_version', sa.String(length=128), nullable=False),
    sa.Column('desired_hash', sa.String(length=64), nullable=False),
    sa.Column('observed_hash', sa.String(length=64), nullable=True),
    sa.Column('ranger_policy_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_reconciliations_policy_key'), 'policy_reconciliations', ['policy_key'], unique=False)
    op.create_table('policy_definition_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('document', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('approved_proposal_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['policy_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('definition_id', 'version', name='uq_policy_definition_version')
    )
    op.create_index('ix_policy_definition_versions_active', 'policy_definition_versions', ['definition_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_policy_definition_versions_active', table_name='policy_definition_versions')
    op.drop_table('policy_definition_versions')
    op.drop_index(op.f('ix_policy_reconciliations_policy_key'), table_name='policy_reconciliations')
    op.drop_table('policy_reconciliations')
    op.drop_table('policy_definitions')
    op.drop_index('ix_governance_proposals_status_created', table_name='governance_proposals')
    op.drop_table('governance_proposals')
    op.drop_index('ix_governance_jobs_claim', table_name='governance_jobs')
    op.drop_table('governance_jobs')
    op.drop_index('ix_audit_events_object', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_access_verifications_verification_group_id'), table_name='access_verifications')
    op.drop_index(op.f('ix_access_verifications_policy_key'), table_name='access_verifications')
    op.drop_table('access_verifications')
    # ### end Alembic commands ###
